{
 "title": "airmon",
 "panels": [
  {
   "title": "Humidity %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "queryText": "SELECT\nstrftime(\"%s\" , timestamp ) as time,\nhumidity\nFROM sensor_data\nORDER BY \"timestamp\";",
     "rawQueryText": "SELECT\nstrftime(\"%s\" , timestamp ) as time,\nhumidity\nFROM sensor_data\nORDER BY \"timestamp\";",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "queryText": "\nSELECT\nstrftime(\"%s\" , timestamp ) as time,\ntemperature\nFROM sensor_data\nORDER BY \"timestamp\";",
     "rawQueryText": "\nSELECT\nstrftime(\"%s\" , timestamp ) as time,\ntemperature\nFROM sensor_data\nORDER BY \"timestamp\";",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "CO",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "queryText": "SELECT\nstrftime(\"%s\" , timestamp ) as time,\nco\nFROM sensor_data\nORDER BY \"timestamp\";",
     "rawQueryText": "SELECT\nstrftime(\"%s\" , timestamp ) as time,\nco\nFROM sensor_data\nORDER BY \"timestamp\";",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "NOx",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "queryText": "SELECT\nstrftime(\"%s\" , timestamp ) as time,\nnox\nFROM sensor_data\nORDER BY \"timestamp\";",
     "rawQueryText": "SELECT\nstrftime(\"%s\" , timestamp ) as time,\nnox\nFROM sensor_data\nORDER BY \"timestamp\";",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "CO2 ppm",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "queryText": "SELECT\nstrftime(\"%s\" , timestamp ) as time,\nco2\nFROM sensor_data\nORDER BY \"timestamp\";",
     "rawQueryText": "SELECT\nstrftime(\"%s\" , timestamp ) as time,\nco2\nFROM sensor_data\nORDER BY \"timestamp\";",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "NH3 ppm",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "queryText": "SELECT\nstrftime(\"%s\" , timestamp ) as time,\nnh3\nFROM sensor_data\nORDER BY \"timestamp\";",
     "rawQueryText": "SELECT\nstrftime(\"%s\" , timestamp ) as time,\nnh3\nFROM sensor_data\nORDER BY \"timestamp\";",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "PM 2.5",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "queryText": "SELECT\nstrftime(\"%s\" , timestamp ) as time,\npm25\nFROM sensor_data\nORDER BY \"timestamp\";",
     "rawQueryText": "SELECT\nstrftime(\"%s\" , timestamp ) as time,\npm25\nFROM sensor_data\nORDER BY \"timestamp\";",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "PM 10",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "queryText": "SELECT\nstrftime(\"%s\" , timestamp ) as time,\npm10\nFROM sensor_data\nORDER BY \"timestamp\";",
     "rawQueryText": "SELECT\nstrftime(\"%s\" , timestamp ) as time,\npm10\nFROM sensor_data\nORDER BY \"timestamp\";",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  }
 ]
}