{
 "title": "Gauges",
 "panels": [
  {
   "title": "Temperature",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT\nstrftime(\"%s\" , timestamp ) as time,\ntemperature\nFROM sensor_data\nORDER BY \"timestamp\"\nDESC LIMIT 1;",
     "rawQueryText": "SELECT\nstrftime(\"%s\" , timestamp ) as time,\ntemperature\nFROM sensor_data\nORDER BY \"timestamp\"\nDESC LIMIT 1;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT\nstrftime(\"%s\" , timestamp ) as time,\nhumidity\nFROM sensor_data\nORDER BY \"timestamp\"\nDESC LIMIT 1;",
     "rawQueryText": "SELECT\nstrftime(\"%s\" , timestamp ) as time,\nhumidity\nFROM sensor_data\nORDER BY \"timestamp\"\nDESC LIMIT 1;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "CO2",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT\nstrftime(\"%s\" , timestamp ) as time,\nco2\nFROM sensor_data\nORDER BY \"timestamp\"\nDESC LIMIT 1;",
     "rawQueryText": "SELECT\nstrftime(\"%s\" , timestamp ) as time,\nco2\nFROM sensor_data\nORDER BY \"timestamp\"\nDESC LIMIT 1;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "NH3",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT\nstrftime(\"%s\" , timestamp ) as time,\nnh3\nFROM sensor_data\nORDER BY \"timestamp\"\nDESC LIMIT 1;",
     "rawQueryText": "SELECT\nstrftime(\"%s\" , timestamp ) as time,\nnh3\nFROM sensor_data\nORDER BY \"timestamp\"\nDESC LIMIT 1;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "NOx",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT\nstrftime(\"%s\" , timestamp ) as time,\nnox\nFROM sensor_data\nORDER BY \"timestamp\"\nDESC LIMIT 1;",
     "rawQueryText": "SELECT\nstrftime(\"%s\" , timestamp ) as time,\nnox\nFROM sensor_data\nORDER BY \"timestamp\"\nDESC LIMIT 1;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "PM 2.5",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "AQI" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT\nstrftime(\"%s\" , timestamp ) as time,\npm25\nFROM sensor_data\nORDER BY \"timestamp\"\nDESC LIMIT 1;",
     "rawQueryText": "SELECT\nstrftime(\"%s\" , timestamp ) as time,\npm25\nFROM sensor_data\nORDER BY \"timestamp\"\nDESC LIMIT 1;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "PM 10",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "AQI" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT\nstrftime(\"%s\" , timestamp ) as time,\npm10\nFROM sensor_data\nORDER BY \"timestamp\"\nDESC LIMIT 1;",
     "rawQueryText": "SELECT\nstrftime(\"%s\" , timestamp ) as time,\npm10\nFROM sensor_data\nORDER BY \"timestamp\"\nDESC LIMIT 1;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  }
 ]
}